language: node_js

warnings_are_errors: false

node_js:
 - "7"
 - "6"

cache:
 yarn: true
 directories:
 - node_modules

install:
 - yarn install

script:
  - yarn run config
  - yarn start
  - yarn buildrun
