export const EXECUTE_CODE = "EXECUTE_CODE";
export const EXECUTE_CODE_FULFILLED = "EXECUTE_CODE_FULFILLED";
export const EXECUTE_CODE_REJECTED = "EXECUTE_CODE_REJECTED";

export const UPDATE_CODE = "UPDATE_CODE";
export const UPDATE_INPUT = "UPDATE_INPUT";
export const UPDATE_FLAGS = "UPDATE_FLAGS";
